### PR TITLE
Add changelog and bump up version for 4.4.0 release

### PR DESCRIPTION
**Pull request by ranjib**
@sethvargo we have to cut a new release for impending ChefDK release to support policy file based specs. Let me know if you want me to cut the release.

### CODE REVIEW

**Comment by sethvargo** [comment]
Go for it - I'm on a plane with terrible wifi

**Comment by ranjib** [comment]
@jtimberman  we are hitting this error 
```sh
 rspec examples/server/spec/client_spec.rb 

server::client
[:client, "*:*"]
  does not raise an exception (FAILED - 1)
[:client, "*:*"]
  searches the Chef Server for clients (FAILED - 2)

Failures:

  1) server::client does not raise an exception
     Failure/Error: expect { chef_run }.to_not raise_error
       expected no Exception, got #<Chef::Exceptions::ValidationFailed: Option admin must be a kind of [TrueClass, FalseClass]!  You passed "true".> with backtrace:
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:157:in `_pv_kind_of'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:67:in `each'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:67:in `block in validate'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:57:in `each'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:57:in `validate'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:97:in `set_or_return'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/api_client.rb:65:in `admin'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/api_client.rb:138:in `from_hash'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/api_client.rb:144:in `json_create'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:85:in `map_to_rb_obj'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:90:in `block in map_to_rb_obj'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:90:in `map'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:90:in `map_to_rb_obj'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:98:in `block in map_hash_to_rb_obj'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:97:in `each'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:97:in `map_hash_to_rb_obj'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:83:in `map_to_rb_obj'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:72:in `from_json'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http/json_output.rb:56:in `handle_response'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:233:in `block in apply_response_middleware'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:231:in `each'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:231:in `inject'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:231:in `apply_response_middleware'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:144:in `request'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/rest.rb:120:in `get'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/search/query.rb:144:in `call_rest_service'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/search/query.rb:87:in `search'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/dsl/data_query.rb:42:in `search'
         # ./lib/chefspec/extensions/chef/data_query.rb:8:in `search'
         # /tmp/d20150918-13423-1c0ea1c/cookbooks/server/recipes/client.rb:1:in `from_file'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/from_file.rb:30:in `instance_eval'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/from_file.rb:30:in `from_file'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/cookbook_version.rb:228:in `load_recipe'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context.rb:174:in `load_recipe'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context.rb:97:in `load'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
         # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/client.rb:486:in `setup_run_context'
         # ./lib/chefspec/solo_runner.rb:117:in `converge'
         # ./lib/chefspec/server_runner.rb:60:in `converge'
         # ./examples/server/spec/client_spec.rb:7:in `block (2 levels) in <top (required)>'
         # ./examples/server/spec/client_spec.rb:11:in `block (3 levels) in <top (required)>'
         # ./lib/chefspec/expect_exception.rb:15:in `matches?'
         # ./examples/server/spec/client_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./examples/server/spec/client_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) server::client searches the Chef Server for clients
     Failure/Error: end.converge(described_recipe)
     Chef::Exceptions::ValidationFailed:
       Option admin must be a kind of [TrueClass, FalseClass]!  You passed "true".
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:157:in `_pv_kind_of'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:67:in `each'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:67:in `block in validate'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:57:in `each'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:57:in `validate'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/params_validate.rb:97:in `set_or_return'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/api_client.rb:65:in `admin'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/api_client.rb:138:in `from_hash'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/api_client.rb:144:in `json_create'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:85:in `map_to_rb_obj'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:90:in `block in map_to_rb_obj'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:90:in `map'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:90:in `map_to_rb_obj'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:98:in `block in map_hash_to_rb_obj'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:97:in `each'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:97:in `map_hash_to_rb_obj'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:83:in `map_to_rb_obj'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/json_compat.rb:72:in `from_json'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http/json_output.rb:56:in `handle_response'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:233:in `block in apply_response_middleware'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:231:in `each'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:231:in `inject'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:231:in `apply_response_middleware'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/http.rb:144:in `request'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/rest.rb:120:in `get'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/search/query.rb:144:in `call_rest_service'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/search/query.rb:87:in `search'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/dsl/data_query.rb:42:in `search'
     # ./lib/chefspec/extensions/chef/data_query.rb:8:in `search'
     # /tmp/d20150918-13423-j39xom/cookbooks/server/recipes/client.rb:1:in `from_file'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/from_file.rb:30:in `instance_eval'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/mixin/from_file.rb:30:in `from_file'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/cookbook_version.rb:228:in `load_recipe'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context.rb:174:in `load_recipe'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/run_context.rb:97:in `load'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
     # ./.bundle/ruby/2.2.0/gems/chef-12.4.1/lib/chef/client.rb:486:in `setup_run_context'
     # ./lib/chefspec/solo_runner.rb:117:in `converge'
     # ./lib/chefspec/server_runner.rb:60:in `converge'
     # ./examples/server/spec/client_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./examples/server/spec/client_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 3.91 seconds (files took 0.6635 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./examples/server/spec/client_spec.rb:10 # server::client does not raise an exception
rspec ./examples/server/spec/client_spec.rb:14 # server::client searches the Chef Server for clients
```
i feel its stemming from chef core.  probably from json conversion.

**Comment by ranjib** [comment]
@sethvargo one chef > 12.4 chef-zero 4.3 is causing the spec failures , client lists, returns json body with admin : true, where true is string instead of boolean :-/ , i dont know a decent way to tell pin chef-zero version in chefspec without breaking older versions of chef (chef 11.x series pins chef-zero to 2.x version)

**Comment by jkeiser** [comment]
I have fixed all the bugs against chef master (I have a PR open with chefspec for that) and released a fixed chef zero, FYI. Would be awesome to get chefspec released (with that PR too) so we can cut a final chefdk 0.9 with latest chefspec and chef 12.5!

**Pull request merged**
