### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
@sethvargo Can you push the gem too please. Thanks

**Comment by sethvargo** [comment]
@tas50 my rubby install is messed up because of Sierra, so I can't. You have owner perms though.

**Comment by tas50** [comment]
@sethvargo I think this is the only Vargo project I don't have access to actually

**Comment by sethvargo** [comment]
```
Owners for gem: chefspec
- tsmith84@gmail.com
- andrew.crump@ieee.org
- dey.ranjib@gmail.com
- sethvargo@gmail.com
```

**Comment by tas50** [comment]
Thanks. Gem is pushed now. Can I get access on this repo too so I can tag the release.

**Pull request merged**
