### PR TITLE
Chef::Recipe include_recipe stubbing

### PR DESCRIPTION
**Pull request by brandocorp**
I'm submitting this mostly to request some feedback. This feature provides a `stub_include_recipe` macro which will block a recipe from actually being loaded within the chef-client run, but still allows the recipe to be registered in the list of loaded recipes.

This avoids the issue where you want to test that a recipe was included via `include_recipe`, but allowing the recipe to be included causes the need to stub out commands, data bag calls, searches, etc. from an external cookbook.

It feels like this more closely resembles the philosophy of unit testing, but as always, I'd appreciate any feedback.

###### Note:
If the `stub_include_recipe` macro isn't used, it will throw an error similar to the behavior of the `stub_command` macro. This breaks a few of the current acceptance tests, which I will gladly fix, if this is deemed useful.

### CODE REVIEW

**Comment by ranjib** [comment]
all existing specs with include_recipe will raise stub exception with this. if we want to stub include_recipe at all, we should not enforce it for those who are fine with included recipes being evaluated,

**Comment by sethvargo** [comment]
I'm pretty :-1: on this. Chef might be unable to properly build the resource collection if you stub an `include_recipe` call. I think this should be more painful for the user than a typical data bag stub. That being said, it's not _that_ complicated:

```ruby
before do
  allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).and_call_original
  allow_any_instance_of(Chef::Recipe).to receive(:include_recipe).with("cookbook::recipe")
end
```

**Comment by brandocorp** [comment]
@sethvargo the example you provided works, but ends up blocking the run_context from seeing that the recipe was included. This means that something like the following will fail your tests

```ruby
it 'includes cookbook::recipe' do
  expect(chef_run).to include_recipe('cookbook::recipe')
end
```

This is what I was attempting to solve. By giving Chef::Recipe it's own include_recipe method (overloading `chef/dsl/include_recipe`), this should be called within the context of a recipe being parsed for resources, but should not break the run_context's ability to load and parse recipes.

Thanks,
Brandon

**Comment by sethvargo** [comment]
@brandocorp 

```ruby
expect_any_instance_of(Chef::Recipe).to receive(:include_recipe).with("cookbook::recipe")
```

Sadly you can't have the best of both worlds. You either want to include the recipe or you don't IMO. I think the added complexity here is not worth the tradeoff (and re-education for users). If you need to stub recipe inclusion, you should go to the RSpec level. I would definitely welcome a PR to add the stuff I just commented to the README, but I don't think we should support another API method for stubbing this function, as it is not something I'd like to encourage.

**Comment by brandocorp** [comment]
Understood. Thanks for the feedback!

**Pull request closed without merging**
