### PR TITLE
Added capabilities for reboot resouce

### PR DESCRIPTION
**Pull request by jwitrick**

### CODE REVIEW

**Comment by sethvargo** [comment]
Thanks!

**Comment by juliandunn** [comment]
Looks like this caused the Travis matrix to fail on the older versions of Chef that don't have a built-in reboot resource.

**Comment by sethvargo** [comment]
Yea, we'll probably need to update the matrix.

**Comment by sethvargo** [comment]
Or skip those tests on older versions

**Comment by miketheman** [comment]
I was trying to figure out a way to tell ChefSpec about "what resources exist from what Chef version" kind of thing and couldn't figure it out. Would be glad to help maintain compat with Chef 11 for a bit longer.

**Pull request merged**
