### PR TITLE
automatically setup matchers

### PR DESCRIPTION
**Pull request by lamont-granquist**
eliminates the need for most custom matchers.

this also eliminates the super goofy magical ChefSpec::API inclusion of all defined module constants under that namespace.   just uses ruby to write into ChefSpec::API and ditches the overly fussy 'encapsulation'.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@tas50 here you go, no more maintaining matchers

**Comment by coderanger** [comment]
Thinking this through further, does this work at all? If you have

```ruby
subject { SoloRunner.converge(whatever }
it { expect(subject).to create_template(...) }
```

it has to compile the matcher expression before the converge runs. This would only work if we always did aggressive (i.e. `let!`) expansions I think?

**Comment by lamont-granquist** [comment]
all the examples pass...

**Comment by lamont-granquist** [comment]
```ruby
  let(:chef_run) { ChefSpec::SoloRunner.new(platform: 'opensuse', version: '42.1').converge(described_recipe) }

  it 'installs a zypper_package with the default action' do
    expect(chef_run).to install_zypper_package('default_action')
    expect(chef_run).to_not install_zypper_package('not_default_action')
  end
```

e.g. that works fine.

and the problem is that if we're going to take the objectspace-searching approach to finding Chef::Resource things, then it has to be done after libraries have been compiled, so we can't overeagerly do this before we've setup a runner and at least done the compilation phase.

we could do things a bit more dynamically and hook class loading, but that also gets messy.  if we mandated that every Chef::Resource had to declare something like `resource_name` or had to touch `provides` or something it might be more doable, but there no 'finalized' or even 'good enough' hook to know when a Chef::Resource subclass has been declared enough to setup matchers for it.  we could add a phase after compiling library/resource classes that would hit matchers, but that is buried down inside chef code.

**Comment by coderanger** [comment]
An easier way to do this would be to put the declaration system in Chef::Resource itself as part of `provides`, but that might be overly familiar? My specific concern is I have a lot of tests that never call `converge` and just use `chef_runner.run_context` or whatever. I could change those all to be blank converges instead but that feels gross and make this less desirable :-/

**Comment by coderanger** [comment]
https://github.com/poise/poise/blob/master/lib/poise/helpers/chefspec_matchers.rb was how I set this up FWIW.

**Comment by lamont-granquist** [comment]
upgraded to hook Chef::Resource methods

**Comment by lamont-granquist** [comment]
also note that all the functional tests already have decent test coverage -- i needed to hook everything this way in order to not blow shit up (the way allowed_actions are subclassed, some resources call resource_name without a provides line, etc, etc).

**Comment by lamont-granquist** [comment]
@tas50 you can smash merge on this and make the world a better place...

**Pull request merged**
