### PR TITLE
Fix yum_repository makecache matcher

### PR DESCRIPTION
**Pull request by tas50**
Get the correct action name after we fixed this in chef/chef

https://github.com/chef/chef/blob/master/lib/chef/resource/yum_repository.rb

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by sethvargo** [comment]
Do we need to do something for BC here? Maybe alias?

**Comment by lamont-granquist** [comment]
grep seems to suggest there should be updates to 4 files here:

```
% egrep -rl make_cache .
./.git/index
./examples/yum_repository/recipes/make_cache.rb
./examples/yum_repository/spec/make_cache_spec.rb
./features/yum_repository.feature
./lib/chefspec/api/yum_repository.rb
```

**Comment by tas50** [comment]
Updated for the examples and specs

**Comment by lamont-granquist** [comment]
and @sethvargo this was just written incorrectly to begin with, chef/chef didn't change, just somehow we started picking this up in chef/chef travis runs this AM and finally it started breaking us...

**Comment by lamont-granquist** [comment]
👍

**Comment by tas50** [comment]
Unfortunately this is fallout from a series of typos we fixed shortly after pushing 12.14. The behavior was correct in the yum cookbook and the matchers there. When I added the matchers here I just copied over the mistake in the 12.14 release.

**Pull request merged**
