### PR TITLE
just remove easy_install

### PR DESCRIPTION
**Pull request by lamont-granquist**
yeah, we could go down the road of testing it only on chef 12.x and
removing it for only chef 13.x, but there's bigger issues to fix
correctly right now, and in a year this will not have caught any
chef 12.x bugs and after that nobody will care.

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@tas50

**Comment by tas50** [comment]
These too https://github.com/sethvargo/chefspec/tree/master/examples/easy_install_package

**Comment by tas50** [comment]
That's also just the testing. Do we actually want to nuke the matchers?

**Comment by lamont-granquist** [comment]
that'll actually hard-break anyone on chef 12 who is actually using the matchers?  dunno how measurably non-zero that number is though.

**Comment by tas50** [comment]
Fair enough we can remove them another time

**Pull request merged**
