### PR TITLE
Remove support for Chef 11, update chef version to test on, use latest Fauxhai

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by thommay** [comment]
:+1: LGTM

**Comment by sethvargo** [comment]
Still waiting on 💚

**Comment by tas50** [comment]
soon...

**Comment by tas50** [comment]
@sethvargo any chance you can nuke the gem cache in travis and kick this job off again. The error I'm seeing generally means there's bad cache.

**Comment by sethvargo** [comment]
@tas50 done

**Comment by tas50** [comment]
Can you kick those 3 failing builds to see if they just magically start working. If not I guess there's something real going on there. 

reboot

**Comment by sethvargo** [comment]
I did @tas50

**Comment by tas50** [comment]
@sethvargo Travis still hates me. I'll try to carve a bit of time out for this post devopsdays

**Comment by tas50** [comment]
@sethvargo I just excluded the subscribes and notification features from <= 12.5.1 since the matcher changes broke testing on those releases. It's less than ideal and I'm open to a better solution, but this gets us a green built with testing of those features on 8 versions of Chef.

**Pull request merged**
